
proxies:
  - name: "🇺🇸|US|美国|@wxgqlfx|237"
    type: vless
    server: 104.168.107.230
    port: 8443
    uuid: b7a3a5b8-fa6d-4339-a0e9-2bff4fe15f1f
    cipher: none
    tls: true
    network: tcp
    flow: xtls-rprx-vision
    servername: aws.amazon.com
    reality-opts:
      public-key: QQHxQK7ocGHvaCmqtW3QapnKiBVd4ZjjM3zhCGVMPS4
      short-id: db68e802226b21cd

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "🇺🇸|US|美国|@wxgqlfx|237"

rules:
  - GEOIP, cn, DIRECT
  - MATCH, Proxy
