proxies:
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|1"
  network: ws
  port: 35123
  reality-opts:
    public-key: ''
    short-id: ''
  server: 123.58.212.186
  servername: 80.qing1.link
  tls: false
  type: vless
  uuid: d342d11e-d424-4583-b36e-524ab1f0afa4
- cipher: none
  flow: xtls-rprx-vision
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|2"
  network: tcp
  port: 31800
  reality-opts:
    public-key: R2gKMF0Tetlnesc1pPkZH9NaOeehw-f5_U9JKG_cLjU
    short-id: ''
  server: 8.217.226.145
  servername: swdist.apple.com
  tls: true
  type: vless
  uuid: 8d901d39-f250-46fd-db03-77276961adbe
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|3"
  network: ws
  port: 25939
  reality-opts:
    public-key: ''
    short-id: ''
  server: 47.243.245.171
  servername: jp000.ylks01.eu.org
  tls: false
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
- cipher: none
  flow: ''
  name: "\U0001F1FA\U0001F1F8|US|\u7F8E\u56FD|@wxgqlfx|4"
  network: ws
  port: 2083
  reality-opts:
    public-key: ''
    short-id: ''
  server: 47.76.77.103
  servername: kk000.ylks.link
  tls: false
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
- cipher: none
  flow: ''
  name: "\U0001F1E8\U0001F1F3|CN|\u4E2D\u56FD|@wxgqlfx|5"
  network: ws
  port: 443
  reality-opts:
    public-key: ''
    short-id: ''
  server: 103.44.255.27
  servername: cfed.tgzdyz2.top
  tls: false
  type: vless
  uuid: 2cd6ed0f-636e-4e6c-9449-5a263d7a0fa5
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|6"
  network: ws
  port: 2096
  reality-opts:
    public-key: ''
    short-id: ''
  server: 47.243.86.79
  servername: zdy000.kpcloud.eu.org
  tls: false
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|7"
  network: ws
  port: 2083
  reality-opts:
    public-key: ''
    short-id: ''
  server: 47.242.232.14
  servername: cfed.tgzdyz2.top
  tls: false
  type: vless
  uuid: 2cd6ed0f-636e-4e6c-9449-5a263d7a0fa5
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|8"
  network: ws
  port: 2083
  reality-opts:
    public-key: ''
    short-id: ''
  server: 8.218.3.12
  servername: jp000.ylks01.eu.org
  tls: false
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
- cipher: auto
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|9"
  network: ws
  port: 443
  reality-opts:
    public-key: ''
    short-id: ''
  server: 172.93.188.140
  servername: t000.ylks.link
  tls: false
  type: vless
  uuid: NISHIKUITAN222
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|10"
  network: ws
  port: 443
  reality-opts:
    public-key: ''
    short-id: ''
  server: 43.154.230.30
  servername: jp000.ylks01.eu.org
  tls: false
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|11"
  network: ws
  port: 2096
  reality-opts:
    public-key: ''
    short-id: ''
  server: 47.243.120.239
  servername: xin000.ylks.link
  tls: false
  type: vless
  uuid: 48198295-b7ba-4b5c-8d85-085d55a6c869
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|12"
  network: ws
  port: 32079
  reality-opts:
    public-key: ''
    short-id: ''
  server: 119.28.189.227
  servername: cfed.tgzdyz2.top
  tls: false
  type: vless
  uuid: 2cd6ed0f-636e-4e6c-9449-5a263d7a0fa5
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|13"
  network: ws
  port: 20018
  reality-opts:
    public-key: ''
    short-id: ''
  server: 103.103.245.205
  servername: zdy000.kpcloud.eu.org
  tls: false
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|14"
  network: ws
  port: 443
  reality-opts:
    public-key: ''
    short-id: ''
  server: 43.155.22.176
  servername: cfed.tgzdyz2.top
  tls: false
  type: vless
  uuid: 2cd6ed0f-636e-4e6c-9449-5a263d7a0fa5
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|15"
  network: ws
  port: 443
  reality-opts:
    public-key: ''
    short-id: ''
  server: 159.138.131.240
  servername: xin000.ylks.link
  tls: false
  type: vless
  uuid: 48198295-b7ba-4b5c-8d85-085d55a6c869
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|16"
  network: ws
  port: 36799
  reality-opts:
    public-key: ''
    short-id: ''
  server: 43.224.50.213
  servername: zdy000.kpcloud.eu.org
  tls: false
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
- cipher: none
  flow: ''
  name: "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|17"
  network: ws
  port: 443
  reality-opts:
    public-key: ''
    short-id: ''
  server: 172.93.165.228
  servername: zdy000.kpcloud.eu.org
  tls: false
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
- cipher: none
  flow: ''
  name: "\U0001F1E9\U0001F1EA|DE|\u5FB7\u56FD|@wxgqlfx|18"
  network: ws
  port: 443
  reality-opts:
    public-key: ''
    short-id: ''
  server: 176.126.114.97
  servername: zdy000.kpcloud.eu.org
  tls: false
  type: vless
  uuid: a13df940-020c-465f-bc89-ee5279b5cd6a
proxy-groups:
- interval: 300
  name: Auto
  proxies:
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|1"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|2"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|3"
  - "\U0001F1FA\U0001F1F8|US|\u7F8E\u56FD|@wxgqlfx|4"
  - "\U0001F1E8\U0001F1F3|CN|\u4E2D\u56FD|@wxgqlfx|5"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|6"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|7"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|8"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|9"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|10"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|11"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|12"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|13"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|14"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|15"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|16"
  - "\U0001F1ED\U0001F1F0|HK|\u9999\u6E2F|@wxgqlfx|17"
  - "\U0001F1E9\U0001F1EA|DE|\u5FB7\u56FD|@wxgqlfx|18"
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- GEOIP, cn, DIRECT
- MATCH, Auto
