
proxies:
  - name: "example-vless"
    type: vless
    server: example.com
    port: 443
    uuid: your-uuid
    cipher: auto
    tls: true
    network: ws
    ws-opts:
      path: /path
      headers:
        Host: example.com

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - "example-vless"

rules:
  - GEOIP, cn, DIRECT
  - MATCH, Proxy
