proxies:
- cipher: none
  flow: ''
  name: "\U0001F1EF\U0001F1F5|JP|\u65E5\u672C|@wxgqlfx|352"
  network: ws
  port: 34307
  reality-opts:
    public-key: ''
    short-id: ''
  server: 150.230.107.234
  servername: v000.ylkszy.eu.org
  tls: false
  type: vless
  uuid: c82f8880-bdd8-4a35-b8e7-ad5aa880f7d0
proxy-groups:
- interval: 300
  name: Auto
  proxies:
  - "\U0001F1EF\U0001F1F5|JP|\u65E5\u672C|@wxgqlfx|352"
  type: url-test
  url: http://www.gstatic.com/generate_204
rules:
- GEOIP, cn, DIRECT
- MATCH, Auto
